services:
  - type: web
    name: spotify-sync
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: SPOTIPY_CLIENT_ID
        value: your_client_id
      - key: SPOTIPY_CLIENT_SECRET
        value: your_client_secret
      - key: SPOTIPY_REDIRECT_URI
        value: your_redirect_uri
      - key: DISCORD_WEBHOOK_URL
        value: your_discord_webhook
